### ISSUE TITLE
Error class is different according to adapters

### ISSUE THREAD

**Issue by gipcompany** [lostisland/faraday-net_http#29]
It seems that when timeout occurs, the error class will be different according to the adapter of Faraday as below. Is there any reason that the difference happens?

* When you use `:net_http` as the adapter, you will get `Faraday::ConnectionFailed`.

```ruby
Faraday.new(request: { timeout: 0.01 }){|f|f.adapter :net_http}.get("https://google.com:81/")
Traceback (most recent call last):
        ... 4 levels...
        16: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/connection.rb:200:in `get'
        15: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/connection.rb:445:in `run_request'
        14: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/rack_builder.rb:153:in `build_response'
        13: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
        12: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/adapter.rb:45:in `connection'
        11: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:65:in `block in call'
        10: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:120:in `perform_request'
         9: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:127:in `request_with_wrapped_block'
         8: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:136:in `request_via_get_method'
         7: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:932:in `start'
         6: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         5: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         4: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/timeout-0.3.0/lib/timeout.rb:186:in `timeout'
         3: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/timeout-0.3.0/lib/timeout.rb:179:in `block in timeout'
         2: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `open'
/Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to google.com:81 (execution expired) (Net::OpenTimeout)
        ... 4 levels...
        16: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/connection.rb:200:in `get'
        15: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/connection.rb:445:in `run_request'
        14: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/rack_builder.rb:153:in `build_response'
        13: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
        12: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/adapter.rb:45:in `connection'
        11: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:65:in `block in call'
        10: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:120:in `perform_request'
         9: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:127:in `request_with_wrapped_block'
         8: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-net_http-2.0.1/lib/faraday/adapter/net_http.rb:136:in `request_via_get_method'
         7: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:932:in `start'
         6: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         5: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         4: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/timeout-0.3.0/lib/timeout.rb:186:in `timeout'
         3: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/timeout-0.3.0/lib/timeout.rb:179:in `block in timeout'
         2: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `open'
/Users/ham/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to google.com:81 (execution expired) (Faraday::ConnectionFailed)
```

* When you use `:httpclient` as the adapter, you will get `Faraday::TimeoutError`.

```ruby
Faraday.new(request: { timeout: 0.01 }){|f|f.adapter :httpclient}.get("https://google.com:81/")
Traceback (most recent call last):
        ... 8 levels...
        16: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/adapter.rb:45:in `connection'
        15: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-httpclient-2.0.1/lib/faraday/adapter/httpclient.rb:45:in `block in call'
        14: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
        13: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        12: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        11: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
        10: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
         9: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
         8: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
         7: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
         6: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/timeout-0.3.0/lib/timeout.rb:186:in `timeout'
         5: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/timeout-0.3.0/lib/timeout.rb:179:in `block in timeout'
         4: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
         3: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
         2: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `create_socket'
         1: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `new'
/Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize': execution expired (HTTPClient::ConnectTimeoutError)
        24: from /Users/ham/.rbenv/versions/2.7.4/bin/irb:23:in `<main>'
        23: from /Users/ham/.rbenv/versions/2.7.4/bin/irb:23:in `load'
        22: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/irb-1.5.0/exe/irb:11:in `<top (required)>'
         5: from (irb):8:in `<main>'
         4: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/connection.rb:200:in `get'
         3: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/connection.rb:445:in `run_request'
         2: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-2.2.0/lib/faraday/rack_builder.rb:153:in `build_response'
         1: from /Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-httpclient-2.0.1/lib/faraday/adapter/httpclient.rb:37:in `call'
/Users/ham/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-httpclient-2.0.1/lib/faraday/adapter/httpclient.rb:59:in `rescue in call': Faraday::TimeoutError
```

**Comment by iMacTia** [comment]
@gipcompany thank you for raising this 🙏 

This is a known issue, particularly hard to fix because of backwards compatibility.
The `net_http` is behaving correctly. In your case the `timeout` is so low that it probably happens while establishing the connection, hence it's an `open_timeout`. Open timeouts should be raised as `ConnectionError`.
Other adapters, like `typhoeus` and `http_client` do not respect this rule and instead simply raise it as `TimeoutError`.

This issue was [discussed at length](https://github.com/lostisland/faraday/issues/718) and we even have [a plan on how to address it](https://github.com/lostisland/faraday/issues/718#issuecomment-387673920), but this was simply unfeasible before Faraday 2.0

Now that Faraday 2.0 is out, we can potentially come back to this by fixing the offending adapters and release them as new major versions 👍.
This will require some time and coordination, but we're going to get there!

**Comment by iMacTia** [comment]
I'm closing this because this is not an issue for the `net_http`, but rather for the other adapters

**Comment by gipcompany** [comment]
@iMacTia

I appreciate your meaningful explanation. I'll keep an eye on the other adapters' updates.
